spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/todobackend"
    username: todobackend
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
logging:
  level:
    web: DEBUG